#pragma once

std::wstring StartupMetaText = L"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<CDataFileMgr__ContentsOfDataFileXml>\n"
" <disabledFiles />\n"
" <includedXmlFiles itemType=\"CDataFileMgr__DataFileArray\" />\n"
" <includedDataFiles />\n"
" <dataFiles itemType=\"CDataFileMgr__DataFile\">\n"
"  <Item>\n"
"   <filename>platform:/data/cdimages/scaleform_platform_pc.rpf</filename>\n"
"   <fileType>RPF_FILE</fileType>\n"
"  </Item>\n"
"  <Item>\n"
"   <filename>platform:/data/ui/value_conversion.rpf</filename>\n"
"   <fileType>RPF_FILE</fileType>\n"
"  </Item>\n"
"  <Item>\n"
"   <filename>platform:/data/ui/widgets.rpf</filename>\n"
"   <fileType>RPF_FILE</fileType>\n"
"  </Item>\n"
"  <Item>\n"
"   <filename>platform:/textures/ui/ui_photo_stickers.rpf</filename>\n"
"   <fileType>RPF_FILE</fileType>\n"
"  </Item>\n"
"  <Item>\n"
"   <filename>platform:/textures/ui/ui_platform.rpf</filename>\n"
"   <fileType>RPF_FILE</fileType>\n"
"  </Item>\n"
"  <Item>\n"
"   <filename>platform:/data/ui/stylesCatalog</filename>\n"
"   <fileType>aWeaponizeDisputants</fileType> <!-- collision -->\n"
"  </Item>\n"
"  <Item>\n"
"   <filename>platform:/data/cdimages/scaleform_frontend.rpf</filename>\n"
"   <fileType>RPF_FILE_PRE_INSTALL</fileType>\n"
"  </Item>\n"
"  <Item>\n"
"   <filename>platform:/textures/ui/ui_startup_textures.rpf</filename>\n"
"   <fileType>RPF_FILE</fileType>\n"
"  </Item>\n"
"  <Item>\n"
"   <filename>platform:/data/ui/startup_data.rpf</filename>\n"
"   <fileType>RPF_FILE</fileType>\n"
"  </Item>\n"
" </dataFiles>\n"
" <contentChangeSets itemType=\"CDataFileMgr__ContentChangeSet\" />\n"
" <patchFiles />\n"
"</CDataFileMgr__ContentsOfDataFileXml>\n";